name: ohclays

packages:
  - ohclays_client
  - ohclays_server
  - ohclays_flutter

scripts:
  prepare:
    description: Prepare the project for hacking
    run: dart pub global activate serverpod_cli && melos bs && melos gen --no-select

  assetgen:
    description: Generate assets
    exec: bash scripts/assetgen.sh
    failFast: true
    concurrency: 1
    orderDependents: true
    packageFilters:
      fileExists: "scripts/assetgen.sh"

  codegen:
    description: Generate code
    exec: bash scripts/codegen.sh
    failFast: true
    concurrency: 1
    orderDependents: true
    packageFilters:
      fileExists: "scripts/codegen.sh"

  docker-start:
    description: Start docker containers
    run: cd ohclays_server && bash scripts/docker-start.sh

  docker-stop:
    description: Stop docker containers
    run: cd ohclays_server && bash scripts/docker-stop.sh

  server-start:
    description: Start server
    run: cd ohclays_server && bash scripts/server-start.sh

  server-migrate:
    description: Migrate server
    run: cd ohclays_server && bash scripts/server-migrate.sh

  gen:
    description: Generate all assets and code
    run: melos assetgen --no-select && melos codegen --no-select


  post-clean:
    description: Run post clean scripts
    exec: bash scripts/clean.sh
    failFast: true
    concurrency: 1
    packageFilters:
      fileExists: "scripts/clean.sh"

command:
  clean:
    hooks:
      post: melos post-clean
